FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .

# build the Nest app
RUN npm run build

FROM node:20-alpine AS production

WORKDIR /usr/src/app

# install only production deps
COPY package*.json ./
RUN npm ci --omit=dev

# copy built files
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 4000

CMD ["node", "dist/main"]
